### ISSUE TITLE
我使用 python train.py --num_frame 3 --epochs 30 --batch_size 1 --learning_rate 0.001 --save_dir exp 會報錯

### ISSUE THREAD

**Issue by alenzenx** [wolfyeva/TrackNetV2#1]
Data dir: TrackNetV2_Dataset
Data input type: 2d
  0%|                                                                                                                                                    | 0/17 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\TrackNetV2-main\train.py", line 61, in <module>
    train_dataset = Badminton_Dataset(root_dir=data_dir, split='train', mode=input_type, num_frame=num_frame, slideing_step=1, debug=debug)
  File "D:\TrackNetV2-main\dataset.py", line 34, in __init__
    self._gen_frame_files()
  File "D:\TrackNetV2-main\dataset.py", line 68, in _gen_frame_files
    match_dir, rally_id = parse.parse('{}/frame/{}', rally_dir)
TypeError: cannot unpack non-iterable NoneType object

**Comment by alenzenx** [comment]
上面是錯誤訊息
